/********************************************************************************
** Form generated from reading UI file 'paradatafile.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PARADATAFILE_H
#define UI_PARADATAFILE_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ParaDataFile
{
public:
    QTabWidget *tabWidget;
    QWidget *tab_1;
    QComboBox *comboBoxRiverMode;
    QComboBox *comboBoxSubsurfaceMode;
    QLabel *textLabel3_22;
    QLabel *textLabel3_20;
    QComboBox *comboBoxSurfaceMode;
    QLabel *textLabel3_21;
    QFrame *line1_2;
    QFrame *line2_3;
    QCheckBox *checkBoxVerboseMode;
    QLabel *textLabel3_23;
    QLabel *textLabel3_24;
    QCheckBox *checkBoxDebugMode;
    QLabel *textLabel3_25;
    QComboBox *comboBoxInitMode;
    QWidget *tab_2;
    QLabel *textLabel1_2;
    QDoubleSpinBox *doubleSpinBoxAbsoluteTolerance;
    QDoubleSpinBox *doubleSpinBoxRelativeTolerance;
    QLabel *textLabel1_3;
    QFrame *line1_3;
    QLabel *textLabel1_4;
    QRadioButton *radioButtonDirectDense;
    QRadioButton *radioButtonIterative;
    QLabel *textLabel1_5;
    QDoubleSpinBox *doubleSpinBoxInitialStep;
    QFrame *line2_4;
    QDoubleSpinBox *doubleSpinBoxMaximumStep;
    QLabel *textLabel1_7;
    QDoubleSpinBox *doubleSpinBoxETStep;
    QLabel *textLabel1_6;
    QLabel *textLabel1_8;
    QDoubleSpinBox *doubleSpinBoxConvergenceThreshold;
    QLabel *textLabel1_9;
    QLabel *textLabel1_10;
    QComboBox *comboBoxGrahmSchmidt;
    QSpinBox *spinBoxKrylovDimension;
    QWidget *tab_3;
    QLabel *textLabel1;
    QLabel *textLabel2;
    QSpinBox *spinBoxStartTime;
    QSpinBox *spinBoxStopTime;
    QComboBox *comboBoxStartStop;
    QFrame *line1;
    QLabel *textLabel3_11;
    QFrame *line2_2;
    QLabel *textLabel3_12;
    QSpinBox *spinBoxRiverbed;
    QLabel *textLabel3_13;
    QSpinBox *spinBoxRiverSurfaceLeftRight;
    QSpinBox *spinBoxRiver;
    QSpinBox *spinBoxRiverUpDown;
    QLabel *textLabel3_14;
    QLabel *textLabel3_15;
    QSpinBox *spinBoxRiverBaseLeftRight;
    QSpinBox *spinBoxInterception;
    QLabel *textLabel3_2;
    QLabel *textLabel3;
    QSpinBox *spinBoxGroundEvaporation;
    QSpinBox *spinBoxSoilMoisture;
    QLabel *textLabel3_5;
    QSpinBox *spinBoxGroundwater;
    QFrame *line2;
    QLabel *textLabel3_6;
    QLabel *textLabel3_3;
    QLabel *textLabel3_9;
    QLabel *textLabel3_10;
    QLabel *textLabel3_4;
    QSpinBox *spinBoxCanopyEvaporation;
    QSpinBox *spinBoxSnow;
    QSpinBox *spinBoxSurface;
    QSpinBox *spinBoxTranspiration;
    QLabel *textLabel3_7;
    QSpinBox *spinBoxRecharge;
    QSpinBox *spinBoxInfiltration;
    QLabel *textLabel3_8;
    QLabel *textLabel3_16;
    QSpinBox *spinBoxRiverbedUpDown;
    QLabel *textLabel3_17;
    QSpinBox *spinBoxRiverbedLeftRight;
    QSpinBox *spinBoxRivertoRiverBed;
    QLabel *textLabel3_18;
    QComboBox *comboBoxOutput;
    QLabel *textLabel3_19;
    QTextBrowser *textBrowserLogs;
    QGroupBox *groupBoxButtons;
    QPushButton *pushButtonHelp;
    QPushButton *pushButtonClose;
    QPushButton *pushButtonRun;
    QFrame *BorderBottom;
    QGroupBox *groupBoxOutput;
    QLabel *textLabelPara;
    QPushButton *pushButtonParaDataFile;
    QLineEdit *lineEditParaDataFile;
    QFrame *BorderTop;

    void setupUi(QDialog *ParaDataFile)
    {
        if (ParaDataFile->objectName().isEmpty())
            ParaDataFile->setObjectName(QStringLiteral("ParaDataFile"));
        ParaDataFile->resize(800, 588);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        ParaDataFile->setPalette(palette);
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(10);
        ParaDataFile->setFont(font);
        tabWidget = new QTabWidget(ParaDataFile);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(5, 21, 781, 281));
        tab_1 = new QWidget();
        tab_1->setObjectName(QStringLiteral("tab_1"));
        comboBoxRiverMode = new QComboBox(tab_1);
        comboBoxRiverMode->addItem(QString());
        comboBoxRiverMode->addItem(QString());
        comboBoxRiverMode->setObjectName(QStringLiteral("comboBoxRiverMode"));
        comboBoxRiverMode->setGeometry(QRect(123, 128, 250, 30));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        comboBoxRiverMode->setFont(font1);
        comboBoxSubsurfaceMode = new QComboBox(tab_1);
        comboBoxSubsurfaceMode->addItem(QString());
        comboBoxSubsurfaceMode->addItem(QString());
        comboBoxSubsurfaceMode->setObjectName(QStringLiteral("comboBoxSubsurfaceMode"));
        comboBoxSubsurfaceMode->setGeometry(QRect(123, 73, 250, 30));
        comboBoxSubsurfaceMode->setFont(font1);
        textLabel3_22 = new QLabel(tab_1);
        textLabel3_22->setObjectName(QStringLiteral("textLabel3_22"));
        textLabel3_22->setGeometry(QRect(20, 128, 91, 31));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        textLabel3_22->setFont(font2);
        textLabel3_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_20 = new QLabel(tab_1);
        textLabel3_20->setObjectName(QStringLiteral("textLabel3_20"));
        textLabel3_20->setGeometry(QRect(20, 17, 91, 31));
        textLabel3_20->setFont(font2);
        textLabel3_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxSurfaceMode = new QComboBox(tab_1);
        comboBoxSurfaceMode->addItem(QString());
        comboBoxSurfaceMode->addItem(QString());
        comboBoxSurfaceMode->setObjectName(QStringLiteral("comboBoxSurfaceMode"));
        comboBoxSurfaceMode->setGeometry(QRect(123, 17, 250, 30));
        comboBoxSurfaceMode->setFont(font1);
        textLabel3_21 = new QLabel(tab_1);
        textLabel3_21->setObjectName(QStringLiteral("textLabel3_21"));
        textLabel3_21->setGeometry(QRect(20, 73, 91, 31));
        textLabel3_21->setFont(font2);
        textLabel3_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line1_2 = new QFrame(tab_1);
        line1_2->setObjectName(QStringLiteral("line1_2"));
        line1_2->setGeometry(QRect(5, 180, 771, 3));
        line1_2->setFrameShape(QFrame::HLine);
        line1_2->setFrameShadow(QFrame::Sunken);
        line2_3 = new QFrame(tab_1);
        line2_3->setObjectName(QStringLiteral("line2_3"));
        line2_3->setGeometry(QRect(389, 5, 3, 165));
        line2_3->setFrameShape(QFrame::VLine);
        line2_3->setFrameShadow(QFrame::Sunken);
        checkBoxVerboseMode = new QCheckBox(tab_1);
        checkBoxVerboseMode->setObjectName(QStringLiteral("checkBoxVerboseMode"));
        checkBoxVerboseMode->setGeometry(QRect(160, 208, 20, 23));
        textLabel3_23 = new QLabel(tab_1);
        textLabel3_23->setObjectName(QStringLiteral("textLabel3_23"));
        textLabel3_23->setGeometry(QRect(20, 203, 111, 31));
        textLabel3_23->setFont(font2);
        textLabel3_24 = new QLabel(tab_1);
        textLabel3_24->setObjectName(QStringLiteral("textLabel3_24"));
        textLabel3_24->setGeometry(QRect(210, 203, 101, 31));
        textLabel3_24->setFont(font2);
        checkBoxDebugMode = new QCheckBox(tab_1);
        checkBoxDebugMode->setObjectName(QStringLiteral("checkBoxDebugMode"));
        checkBoxDebugMode->setGeometry(QRect(340, 208, 20, 23));
        checkBoxDebugMode->setChecked(true);
        textLabel3_25 = new QLabel(tab_1);
        textLabel3_25->setObjectName(QStringLiteral("textLabel3_25"));
        textLabel3_25->setGeometry(QRect(410, 17, 91, 31));
        textLabel3_25->setFont(font2);
        comboBoxInitMode = new QComboBox(tab_1);
        comboBoxInitMode->addItem(QString());
        comboBoxInitMode->addItem(QString());
        comboBoxInitMode->addItem(QString());
        comboBoxInitMode->setObjectName(QStringLiteral("comboBoxInitMode"));
        comboBoxInitMode->setGeometry(QRect(510, 17, 250, 30));
        comboBoxInitMode->setFont(font1);
        tabWidget->addTab(tab_1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        textLabel1_2 = new QLabel(tab_2);
        textLabel1_2->setObjectName(QStringLiteral("textLabel1_2"));
        textLabel1_2->setGeometry(QRect(400, 207, 151, 31));
        QFont font3;
        font3.setFamily(QStringLiteral("Arial"));
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setWeight(75);
        textLabel1_2->setFont(font3);
        textLabel1_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxAbsoluteTolerance = new QDoubleSpinBox(tab_2);
        doubleSpinBoxAbsoluteTolerance->setObjectName(QStringLiteral("doubleSpinBoxAbsoluteTolerance"));
        doubleSpinBoxAbsoluteTolerance->setGeometry(QRect(560, 208, 200, 29));
        QFont font4;
        font4.setFamily(QStringLiteral("Arial"));
        font4.setPointSize(11);
        font4.setBold(true);
        font4.setWeight(75);
        doubleSpinBoxAbsoluteTolerance->setFont(font4);
        doubleSpinBoxAbsoluteTolerance->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxAbsoluteTolerance->setDecimals(6);
        doubleSpinBoxAbsoluteTolerance->setMaximum(1);
        doubleSpinBoxAbsoluteTolerance->setSingleStep(0.0001);
        doubleSpinBoxAbsoluteTolerance->setValue(0.0001);
        doubleSpinBoxRelativeTolerance = new QDoubleSpinBox(tab_2);
        doubleSpinBoxRelativeTolerance->setObjectName(QStringLiteral("doubleSpinBoxRelativeTolerance"));
        doubleSpinBoxRelativeTolerance->setGeometry(QRect(560, 169, 200, 29));
        doubleSpinBoxRelativeTolerance->setFont(font4);
        doubleSpinBoxRelativeTolerance->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxRelativeTolerance->setDecimals(6);
        doubleSpinBoxRelativeTolerance->setMaximum(1);
        doubleSpinBoxRelativeTolerance->setSingleStep(0.001);
        doubleSpinBoxRelativeTolerance->setValue(0.001);
        textLabel1_3 = new QLabel(tab_2);
        textLabel1_3->setObjectName(QStringLiteral("textLabel1_3"));
        textLabel1_3->setGeometry(QRect(400, 168, 151, 31));
        textLabel1_3->setFont(font3);
        textLabel1_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line1_3 = new QFrame(tab_2);
        line1_3->setObjectName(QStringLiteral("line1_3"));
        line1_3->setGeometry(QRect(5, 56, 761, 3));
        line1_3->setFrameShape(QFrame::HLine);
        line1_3->setFrameShadow(QFrame::Sunken);
        textLabel1_4 = new QLabel(tab_2);
        textLabel1_4->setObjectName(QStringLiteral("textLabel1_4"));
        textLabel1_4->setGeometry(QRect(170, 12, 131, 31));
        textLabel1_4->setFont(font2);
        textLabel1_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        radioButtonDirectDense = new QRadioButton(tab_2);
        radioButtonDirectDense->setObjectName(QStringLiteral("radioButtonDirectDense"));
        radioButtonDirectDense->setEnabled(false);
        radioButtonDirectDense->setGeometry(QRect(310, 16, 121, 23));
        radioButtonDirectDense->setFont(font2);
        radioButtonIterative = new QRadioButton(tab_2);
        radioButtonIterative->setObjectName(QStringLiteral("radioButtonIterative"));
        radioButtonIterative->setGeometry(QRect(470, 16, 121, 23));
        radioButtonIterative->setFont(font2);
        radioButtonIterative->setChecked(true);
        textLabel1_5 = new QLabel(tab_2);
        textLabel1_5->setObjectName(QStringLiteral("textLabel1_5"));
        textLabel1_5->setGeometry(QRect(420, 90, 131, 31));
        textLabel1_5->setFont(font3);
        textLabel1_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxInitialStep = new QDoubleSpinBox(tab_2);
        doubleSpinBoxInitialStep->setObjectName(QStringLiteral("doubleSpinBoxInitialStep"));
        doubleSpinBoxInitialStep->setGeometry(QRect(560, 90, 200, 29));
        doubleSpinBoxInitialStep->setFont(font4);
        doubleSpinBoxInitialStep->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxInitialStep->setDecimals(6);
        doubleSpinBoxInitialStep->setMaximum(1);
        doubleSpinBoxInitialStep->setSingleStep(1e-5);
        doubleSpinBoxInitialStep->setValue(1e-5);
        line2_4 = new QFrame(tab_2);
        line2_4->setObjectName(QStringLiteral("line2_4"));
        line2_4->setGeometry(QRect(388, 64, 3, 183));
        line2_4->setFrameShape(QFrame::VLine);
        line2_4->setFrameShadow(QFrame::Sunken);
        doubleSpinBoxMaximumStep = new QDoubleSpinBox(tab_2);
        doubleSpinBoxMaximumStep->setObjectName(QStringLiteral("doubleSpinBoxMaximumStep"));
        doubleSpinBoxMaximumStep->setGeometry(QRect(560, 131, 200, 29));
        doubleSpinBoxMaximumStep->setFont(font4);
        doubleSpinBoxMaximumStep->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxMaximumStep->setDecimals(6);
        doubleSpinBoxMaximumStep->setMaximum(1440);
        doubleSpinBoxMaximumStep->setSingleStep(1);
        doubleSpinBoxMaximumStep->setValue(30);
        textLabel1_7 = new QLabel(tab_2);
        textLabel1_7->setObjectName(QStringLiteral("textLabel1_7"));
        textLabel1_7->setGeometry(QRect(420, 130, 131, 31));
        textLabel1_7->setFont(font3);
        textLabel1_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxETStep = new QDoubleSpinBox(tab_2);
        doubleSpinBoxETStep->setObjectName(QStringLiteral("doubleSpinBoxETStep"));
        doubleSpinBoxETStep->setGeometry(QRect(155, 208, 220, 29));
        doubleSpinBoxETStep->setFont(font4);
        doubleSpinBoxETStep->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxETStep->setDecimals(6);
        doubleSpinBoxETStep->setMaximum(1);
        doubleSpinBoxETStep->setSingleStep(1);
        doubleSpinBoxETStep->setValue(1);
        textLabel1_6 = new QLabel(tab_2);
        textLabel1_6->setObjectName(QStringLiteral("textLabel1_6"));
        textLabel1_6->setGeometry(QRect(10, 207, 131, 31));
        textLabel1_6->setFont(font3);
        textLabel1_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel1_8 = new QLabel(tab_2);
        textLabel1_8->setObjectName(QStringLiteral("textLabel1_8"));
        textLabel1_8->setGeometry(QRect(10, 163, 131, 31));
        textLabel1_8->setFont(font3);
        textLabel1_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxConvergenceThreshold = new QDoubleSpinBox(tab_2);
        doubleSpinBoxConvergenceThreshold->setObjectName(QStringLiteral("doubleSpinBoxConvergenceThreshold"));
        doubleSpinBoxConvergenceThreshold->setGeometry(QRect(155, 164, 220, 29));
        doubleSpinBoxConvergenceThreshold->setFont(font4);
        doubleSpinBoxConvergenceThreshold->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxConvergenceThreshold->setDecimals(6);
        doubleSpinBoxConvergenceThreshold->setMaximum(1);
        doubleSpinBoxConvergenceThreshold->setSingleStep(1);
        doubleSpinBoxConvergenceThreshold->setValue(0);
        textLabel1_9 = new QLabel(tab_2);
        textLabel1_9->setObjectName(QStringLiteral("textLabel1_9"));
        textLabel1_9->setGeometry(QRect(10, 118, 131, 31));
        textLabel1_9->setFont(font3);
        textLabel1_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel1_10 = new QLabel(tab_2);
        textLabel1_10->setObjectName(QStringLiteral("textLabel1_10"));
        textLabel1_10->setGeometry(QRect(10, 73, 131, 31));
        textLabel1_10->setFont(font3);
        textLabel1_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxGrahmSchmidt = new QComboBox(tab_2);
        comboBoxGrahmSchmidt->addItem(QString());
        comboBoxGrahmSchmidt->addItem(QString());
        comboBoxGrahmSchmidt->setObjectName(QStringLiteral("comboBoxGrahmSchmidt"));
        comboBoxGrahmSchmidt->setGeometry(QRect(155, 74, 220, 30));
        comboBoxGrahmSchmidt->setFont(font1);
        spinBoxKrylovDimension = new QSpinBox(tab_2);
        spinBoxKrylovDimension->setObjectName(QStringLiteral("spinBoxKrylovDimension"));
        spinBoxKrylovDimension->setGeometry(QRect(155, 120, 220, 29));
        spinBoxKrylovDimension->setFont(font4);
        spinBoxKrylovDimension->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        textLabel1 = new QLabel(tab_3);
        textLabel1->setObjectName(QStringLiteral("textLabel1"));
        textLabel1->setGeometry(QRect(12, 10, 121, 31));
        textLabel1->setFont(font2);
        textLabel2 = new QLabel(tab_3);
        textLabel2->setObjectName(QStringLiteral("textLabel2"));
        textLabel2->setGeometry(QRect(290, 10, 121, 31));
        textLabel2->setFont(font2);
        spinBoxStartTime = new QSpinBox(tab_3);
        spinBoxStartTime->setObjectName(QStringLiteral("spinBoxStartTime"));
        spinBoxStartTime->setGeometry(QRect(96, 10, 150, 29));
        spinBoxStartTime->setFont(font1);
        spinBoxStartTime->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxStopTime = new QSpinBox(tab_3);
        spinBoxStopTime->setObjectName(QStringLiteral("spinBoxStopTime"));
        spinBoxStopTime->setGeometry(QRect(370, 10, 150, 29));
        spinBoxStopTime->setFont(font1);
        spinBoxStopTime->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxStopTime->setValue(2);
        comboBoxStartStop = new QComboBox(tab_3);
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->addItem(QString());
        comboBoxStartStop->setObjectName(QStringLiteral("comboBoxStartStop"));
        comboBoxStartStop->setGeometry(QRect(557, 10, 210, 30));
        comboBoxStartStop->setFont(font2);
        line1 = new QFrame(tab_3);
        line1->setObjectName(QStringLiteral("line1"));
        line1->setGeometry(QRect(6, 47, 771, 3));
        line1->setFrameShape(QFrame::HLine);
        line1->setFrameShadow(QFrame::Sunken);
        textLabel3_11 = new QLabel(tab_3);
        textLabel3_11->setObjectName(QStringLiteral("textLabel3_11"));
        textLabel3_11->setGeometry(QRect(200, 100, 91, 31));
        QFont font5;
        font5.setBold(true);
        font5.setWeight(75);
        textLabel3_11->setFont(font5);
        textLabel3_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line2_2 = new QFrame(tab_3);
        line2_2->setObjectName(QStringLiteral("line2_2"));
        line2_2->setGeometry(QRect(383, 58, 3, 191));
        line2_2->setFrameShape(QFrame::VLine);
        line2_2->setFrameShadow(QFrame::Sunken);
        textLabel3_12 = new QLabel(tab_3);
        textLabel3_12->setObjectName(QStringLiteral("textLabel3_12"));
        textLabel3_12->setGeometry(QRect(9, 100, 91, 31));
        textLabel3_12->setFont(font5);
        textLabel3_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbed = new QSpinBox(tab_3);
        spinBoxRiverbed->setObjectName(QStringLiteral("spinBoxRiverbed"));
        spinBoxRiverbed->setGeometry(QRect(300, 100, 70, 29));
        QFont font6;
        font6.setPointSize(11);
        spinBoxRiverbed->setFont(font6);
        spinBoxRiverbed->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbed->setValue(1);
        textLabel3_13 = new QLabel(tab_3);
        textLabel3_13->setObjectName(QStringLiteral("textLabel3_13"));
        textLabel3_13->setGeometry(QRect(9, 136, 91, 31));
        textLabel3_13->setFont(font5);
        textLabel3_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverSurfaceLeftRight = new QSpinBox(tab_3);
        spinBoxRiverSurfaceLeftRight->setObjectName(QStringLiteral("spinBoxRiverSurfaceLeftRight"));
        spinBoxRiverSurfaceLeftRight->setGeometry(QRect(120, 174, 70, 29));
        spinBoxRiverSurfaceLeftRight->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverSurfaceLeftRight->setValue(1);
        spinBoxRiver = new QSpinBox(tab_3);
        spinBoxRiver->setObjectName(QStringLiteral("spinBoxRiver"));
        spinBoxRiver->setGeometry(QRect(120, 100, 70, 29));
        spinBoxRiver->setFont(font6);
        spinBoxRiver->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiver->setValue(1);
        spinBoxRiverUpDown = new QSpinBox(tab_3);
        spinBoxRiverUpDown->setObjectName(QStringLiteral("spinBoxRiverUpDown"));
        spinBoxRiverUpDown->setGeometry(QRect(120, 136, 70, 29));
        spinBoxRiverUpDown->setFont(font6);
        spinBoxRiverUpDown->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverUpDown->setValue(1);
        textLabel3_14 = new QLabel(tab_3);
        textLabel3_14->setObjectName(QStringLiteral("textLabel3_14"));
        textLabel3_14->setGeometry(QRect(30, 174, 70, 31));
        QFont font7;
        font7.setPointSize(10);
        font7.setBold(true);
        font7.setWeight(75);
        textLabel3_14->setFont(font7);
        textLabel3_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_15 = new QLabel(tab_3);
        textLabel3_15->setObjectName(QStringLiteral("textLabel3_15"));
        textLabel3_15->setGeometry(QRect(9, 212, 91, 31));
        textLabel3_15->setFont(font5);
        textLabel3_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverBaseLeftRight = new QSpinBox(tab_3);
        spinBoxRiverBaseLeftRight->setObjectName(QStringLiteral("spinBoxRiverBaseLeftRight"));
        spinBoxRiverBaseLeftRight->setGeometry(QRect(120, 212, 70, 29));
        spinBoxRiverBaseLeftRight->setFont(font6);
        spinBoxRiverBaseLeftRight->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverBaseLeftRight->setValue(1);
        spinBoxInterception = new QSpinBox(tab_3);
        spinBoxInterception->setObjectName(QStringLiteral("spinBoxInterception"));
        spinBoxInterception->setGeometry(QRect(510, 60, 70, 29));
        spinBoxInterception->setFont(font6);
        spinBoxInterception->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxInterception->setValue(1);
        textLabel3_2 = new QLabel(tab_3);
        textLabel3_2->setObjectName(QStringLiteral("textLabel3_2"));
        textLabel3_2->setGeometry(QRect(376, 98, 121, 31));
        textLabel3_2->setFont(font5);
        textLabel3_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3 = new QLabel(tab_3);
        textLabel3->setObjectName(QStringLiteral("textLabel3"));
        textLabel3->setGeometry(QRect(376, 60, 121, 31));
        textLabel3->setFont(font5);
        textLabel3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxGroundEvaporation = new QSpinBox(tab_3);
        spinBoxGroundEvaporation->setObjectName(QStringLiteral("spinBoxGroundEvaporation"));
        spinBoxGroundEvaporation->setGeometry(QRect(693, 212, 70, 29));
        spinBoxGroundEvaporation->setFont(font6);
        spinBoxGroundEvaporation->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxGroundEvaporation->setValue(1);
        spinBoxSoilMoisture = new QSpinBox(tab_3);
        spinBoxSoilMoisture->setObjectName(QStringLiteral("spinBoxSoilMoisture"));
        spinBoxSoilMoisture->setGeometry(QRect(510, 174, 70, 29));
        spinBoxSoilMoisture->setFont(font6);
        spinBoxSoilMoisture->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxSoilMoisture->setValue(1);
        textLabel3_5 = new QLabel(tab_3);
        textLabel3_5->setObjectName(QStringLiteral("textLabel3_5"));
        textLabel3_5->setGeometry(QRect(376, 212, 121, 31));
        textLabel3_5->setFont(font5);
        textLabel3_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxGroundwater = new QSpinBox(tab_3);
        spinBoxGroundwater->setObjectName(QStringLiteral("spinBoxGroundwater"));
        spinBoxGroundwater->setGeometry(QRect(510, 212, 70, 29));
        spinBoxGroundwater->setFont(font6);
        spinBoxGroundwater->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxGroundwater->setValue(1);
        line2 = new QFrame(tab_3);
        line2->setObjectName(QStringLiteral("line2"));
        line2->setGeometry(QRect(590, 58, 3, 191));
        line2->setFrameShape(QFrame::VLine);
        line2->setFrameShadow(QFrame::Sunken);
        textLabel3_6 = new QLabel(tab_3);
        textLabel3_6->setObjectName(QStringLiteral("textLabel3_6"));
        textLabel3_6->setGeometry(QRect(560, 212, 121, 31));
        textLabel3_6->setFont(font5);
        textLabel3_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_3 = new QLabel(tab_3);
        textLabel3_3->setObjectName(QStringLiteral("textLabel3_3"));
        textLabel3_3->setGeometry(QRect(406, 136, 91, 31));
        textLabel3_3->setFont(font5);
        textLabel3_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_9 = new QLabel(tab_3);
        textLabel3_9->setObjectName(QStringLiteral("textLabel3_9"));
        textLabel3_9->setGeometry(QRect(560, 98, 121, 31));
        textLabel3_9->setFont(font5);
        textLabel3_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_10 = new QLabel(tab_3);
        textLabel3_10->setObjectName(QStringLiteral("textLabel3_10"));
        textLabel3_10->setGeometry(QRect(560, 60, 121, 31));
        textLabel3_10->setFont(font5);
        textLabel3_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_4 = new QLabel(tab_3);
        textLabel3_4->setObjectName(QStringLiteral("textLabel3_4"));
        textLabel3_4->setGeometry(QRect(376, 174, 121, 31));
        textLabel3_4->setFont(font7);
        textLabel3_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxCanopyEvaporation = new QSpinBox(tab_3);
        spinBoxCanopyEvaporation->setObjectName(QStringLiteral("spinBoxCanopyEvaporation"));
        spinBoxCanopyEvaporation->setGeometry(QRect(693, 136, 70, 29));
        spinBoxCanopyEvaporation->setFont(font6);
        spinBoxCanopyEvaporation->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxCanopyEvaporation->setValue(1);
        spinBoxSnow = new QSpinBox(tab_3);
        spinBoxSnow->setObjectName(QStringLiteral("spinBoxSnow"));
        spinBoxSnow->setGeometry(QRect(510, 98, 70, 29));
        spinBoxSnow->setFont(font6);
        spinBoxSnow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxSnow->setValue(1);
        spinBoxSurface = new QSpinBox(tab_3);
        spinBoxSurface->setObjectName(QStringLiteral("spinBoxSurface"));
        spinBoxSurface->setGeometry(QRect(510, 136, 70, 29));
        spinBoxSurface->setFont(font6);
        spinBoxSurface->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxSurface->setValue(1);
        spinBoxTranspiration = new QSpinBox(tab_3);
        spinBoxTranspiration->setObjectName(QStringLiteral("spinBoxTranspiration"));
        spinBoxTranspiration->setGeometry(QRect(693, 174, 70, 29));
        spinBoxTranspiration->setFont(font6);
        spinBoxTranspiration->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxTranspiration->setValue(1);
        textLabel3_7 = new QLabel(tab_3);
        textLabel3_7->setObjectName(QStringLiteral("textLabel3_7"));
        textLabel3_7->setGeometry(QRect(589, 136, 91, 31));
        textLabel3_7->setFont(font7);
        textLabel3_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRecharge = new QSpinBox(tab_3);
        spinBoxRecharge->setObjectName(QStringLiteral("spinBoxRecharge"));
        spinBoxRecharge->setGeometry(QRect(693, 98, 70, 29));
        spinBoxRecharge->setFont(font6);
        spinBoxRecharge->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRecharge->setValue(1);
        spinBoxInfiltration = new QSpinBox(tab_3);
        spinBoxInfiltration->setObjectName(QStringLiteral("spinBoxInfiltration"));
        spinBoxInfiltration->setGeometry(QRect(693, 60, 70, 29));
        spinBoxInfiltration->setFont(font6);
        spinBoxInfiltration->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxInfiltration->setValue(1);
        textLabel3_8 = new QLabel(tab_3);
        textLabel3_8->setObjectName(QStringLiteral("textLabel3_8"));
        textLabel3_8->setGeometry(QRect(560, 174, 121, 31));
        textLabel3_8->setFont(font5);
        textLabel3_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabel3_16 = new QLabel(tab_3);
        textLabel3_16->setObjectName(QStringLiteral("textLabel3_16"));
        textLabel3_16->setGeometry(QRect(201, 212, 91, 31));
        textLabel3_16->setFont(font5);
        textLabel3_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbedUpDown = new QSpinBox(tab_3);
        spinBoxRiverbedUpDown->setObjectName(QStringLiteral("spinBoxRiverbedUpDown"));
        spinBoxRiverbedUpDown->setGeometry(QRect(300, 136, 70, 29));
        spinBoxRiverbedUpDown->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbedUpDown->setValue(1);
        textLabel3_17 = new QLabel(tab_3);
        textLabel3_17->setObjectName(QStringLiteral("textLabel3_17"));
        textLabel3_17->setGeometry(QRect(201, 174, 91, 31));
        textLabel3_17->setFont(font5);
        textLabel3_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbedLeftRight = new QSpinBox(tab_3);
        spinBoxRiverbedLeftRight->setObjectName(QStringLiteral("spinBoxRiverbedLeftRight"));
        spinBoxRiverbedLeftRight->setGeometry(QRect(300, 174, 70, 29));
        spinBoxRiverbedLeftRight->setFont(font6);
        spinBoxRiverbedLeftRight->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRiverbedLeftRight->setValue(1);
        spinBoxRivertoRiverBed = new QSpinBox(tab_3);
        spinBoxRivertoRiverBed->setObjectName(QStringLiteral("spinBoxRivertoRiverBed"));
        spinBoxRivertoRiverBed->setGeometry(QRect(300, 212, 70, 29));
        spinBoxRivertoRiverBed->setFont(font6);
        spinBoxRivertoRiverBed->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBoxRivertoRiverBed->setValue(1);
        textLabel3_18 = new QLabel(tab_3);
        textLabel3_18->setObjectName(QStringLiteral("textLabel3_18"));
        textLabel3_18->setGeometry(QRect(201, 136, 91, 31));
        textLabel3_18->setFont(font7);
        textLabel3_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxOutput = new QComboBox(tab_3);
        comboBoxOutput->addItem(QString());
        comboBoxOutput->addItem(QString());
        comboBoxOutput->addItem(QString());
        comboBoxOutput->addItem(QString());
        comboBoxOutput->addItem(QString());
        comboBoxOutput->addItem(QString());
        comboBoxOutput->setObjectName(QStringLiteral("comboBoxOutput"));
        comboBoxOutput->setGeometry(QRect(160, 60, 210, 30));
        comboBoxOutput->setFont(font1);
        textLabel3_19 = new QLabel(tab_3);
        textLabel3_19->setObjectName(QStringLiteral("textLabel3_19"));
        textLabel3_19->setGeometry(QRect(8, 60, 141, 31));
        textLabel3_19->setFont(font2);
        tabWidget->addTab(tab_3, QString());
        textBrowserLogs = new QTextBrowser(ParaDataFile);
        textBrowserLogs->setObjectName(QStringLiteral("textBrowserLogs"));
        textBrowserLogs->setGeometry(QRect(5, 427, 781, 141));
        textBrowserLogs->setLineWrapMode(QTextEdit::NoWrap);
        groupBoxButtons = new QGroupBox(ParaDataFile);
        groupBoxButtons->setObjectName(QStringLiteral("groupBoxButtons"));
        groupBoxButtons->setGeometry(QRect(5, 383, 781, 41));
        pushButtonHelp = new QPushButton(groupBoxButtons);
        pushButtonHelp->setObjectName(QStringLiteral("pushButtonHelp"));
        pushButtonHelp->setEnabled(false);
        pushButtonHelp->setGeometry(QRect(10, 6, 113, 32));
        pushButtonHelp->setFont(font2);
        pushButtonHelp->setAutoDefault(false);
        pushButtonClose = new QPushButton(groupBoxButtons);
        pushButtonClose->setObjectName(QStringLiteral("pushButtonClose"));
        pushButtonClose->setGeometry(QRect(540, 6, 113, 32));
        pushButtonClose->setFont(font2);
        pushButtonClose->setAutoDefault(false);
        pushButtonRun = new QPushButton(groupBoxButtons);
        pushButtonRun->setObjectName(QStringLiteral("pushButtonRun"));
        pushButtonRun->setGeometry(QRect(657, 6, 113, 32));
        pushButtonRun->setFont(font2);
        pushButtonRun->setAutoDefault(false);
        BorderBottom = new QFrame(ParaDataFile);
        BorderBottom->setObjectName(QStringLiteral("BorderBottom"));
        BorderBottom->setGeometry(QRect(0, 572, 800, 20));
        BorderBottom->setBaseSize(QSize(0, 0));
        QPalette palette1;
        QBrush brush5(QColor(0, 51, 153, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        QBrush brush6(QColor(128, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush6);
        QBrush brush7(QColor(192, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush7);
        QBrush brush8(QColor(160, 0, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        QBrush brush9(QColor(64, 0, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush9);
        QBrush brush10(QColor(85, 0, 0, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderBottom->setPalette(palette1);
        BorderBottom->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderBottom->setFrameShadow(QFrame::Plain);
        BorderBottom->setLineWidth(12);
        BorderBottom->setMidLineWidth(0);
        BorderBottom->setFrameShape(QFrame::HLine);
        groupBoxOutput = new QGroupBox(ParaDataFile);
        groupBoxOutput->setObjectName(QStringLiteral("groupBoxOutput"));
        groupBoxOutput->setGeometry(QRect(5, 304, 781, 81));
        textLabelPara = new QLabel(groupBoxOutput);
        textLabelPara->setObjectName(QStringLiteral("textLabelPara"));
        textLabelPara->setGeometry(QRect(321, 10, 131, 31));
        textLabelPara->setFont(font2);
        textLabelPara->setAlignment(Qt::AlignCenter);
        pushButtonParaDataFile = new QPushButton(groupBoxOutput);
        pushButtonParaDataFile->setObjectName(QStringLiteral("pushButtonParaDataFile"));
        pushButtonParaDataFile->setGeometry(QRect(673, 10, 98, 32));
        pushButtonParaDataFile->setFont(font2);
        pushButtonParaDataFile->setAutoDefault(false);
        lineEditParaDataFile = new QLineEdit(groupBoxOutput);
        lineEditParaDataFile->setObjectName(QStringLiteral("lineEditParaDataFile"));
        lineEditParaDataFile->setGeometry(QRect(0, 44, 771, 29));
        lineEditParaDataFile->setFont(font1);
        BorderTop = new QFrame(ParaDataFile);
        BorderTop->setObjectName(QStringLiteral("BorderTop"));
        BorderTop->setGeometry(QRect(0, -4, 800, 20));
        BorderTop->setBaseSize(QSize(0, 0));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderTop->setPalette(palette2);
        BorderTop->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderTop->setFrameShadow(QFrame::Plain);
        BorderTop->setLineWidth(12);
        BorderTop->setMidLineWidth(0);
        BorderTop->setFrameShape(QFrame::HLine);

        retranslateUi(ParaDataFile);

        tabWidget->setCurrentIndex(2);
        comboBoxRiverMode->setCurrentIndex(1);
        comboBoxSubsurfaceMode->setCurrentIndex(1);
        comboBoxSurfaceMode->setCurrentIndex(1);
        comboBoxInitMode->setCurrentIndex(2);
        comboBoxGrahmSchmidt->setCurrentIndex(0);
        comboBoxStartStop->setCurrentIndex(0);
        comboBoxOutput->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ParaDataFile);
    } // setupUi

    void retranslateUi(QDialog *ParaDataFile)
    {
        ParaDataFile->setWindowTitle(QApplication::translate("ParaDataFile", "Para Data File", nullptr));
        comboBoxRiverMode->setItemText(0, QApplication::translate("ParaDataFile", "Kinematic", nullptr));
        comboBoxRiverMode->setItemText(1, QApplication::translate("ParaDataFile", "Diffusion", nullptr));

        comboBoxRiverMode->setCurrentText(QApplication::translate("ParaDataFile", "Diffusion", nullptr));
        comboBoxSubsurfaceMode->setItemText(0, QApplication::translate("ParaDataFile", "Shallow", nullptr));
        comboBoxSubsurfaceMode->setItemText(1, QApplication::translate("ParaDataFile", "Deep", nullptr));

        comboBoxSubsurfaceMode->setCurrentText(QApplication::translate("ParaDataFile", "Deep", nullptr));
        textLabel3_22->setText(QApplication::translate("ParaDataFile", "River", nullptr));
        textLabel3_20->setText(QApplication::translate("ParaDataFile", "Surface", nullptr));
        comboBoxSurfaceMode->setItemText(0, QApplication::translate("ParaDataFile", "Kinematic", nullptr));
        comboBoxSurfaceMode->setItemText(1, QApplication::translate("ParaDataFile", "Diffusion", nullptr));

        comboBoxSurfaceMode->setCurrentText(QApplication::translate("ParaDataFile", "Diffusion", nullptr));
        textLabel3_21->setText(QApplication::translate("ParaDataFile", "Subsurface", nullptr));
        checkBoxVerboseMode->setText(QString());
        textLabel3_23->setText(QApplication::translate("ParaDataFile", "Verbose Mode", nullptr));
        textLabel3_24->setText(QApplication::translate("ParaDataFile", "Debug Mode", nullptr));
        checkBoxDebugMode->setText(QString());
        textLabel3_25->setText(QApplication::translate("ParaDataFile", "Initial Mode", nullptr));
        comboBoxInitMode->setItemText(0, QApplication::translate("ParaDataFile", "Relax", nullptr));
        comboBoxInitMode->setItemText(1, QApplication::translate("ParaDataFile", "Att/Riv", nullptr));
        comboBoxInitMode->setItemText(2, QApplication::translate("ParaDataFile", "Init File", nullptr));

        comboBoxInitMode->setCurrentText(QApplication::translate("ParaDataFile", "Init File", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_1), QApplication::translate("ParaDataFile", " Model Process Parameters", nullptr));
        textLabel1_2->setText(QApplication::translate("ParaDataFile", "Absolute Tolerance", nullptr));
        textLabel1_3->setText(QApplication::translate("ParaDataFile", "Relative Tolerance", nullptr));
        textLabel1_4->setText(QApplication::translate("ParaDataFile", "Solver Type", nullptr));
        radioButtonDirectDense->setText(QApplication::translate("ParaDataFile", "Direct Dense", nullptr));
        radioButtonIterative->setText(QApplication::translate("ParaDataFile", "Iterative", nullptr));
        textLabel1_5->setText(QApplication::translate("ParaDataFile", "Initial Step", nullptr));
        textLabel1_7->setText(QApplication::translate("ParaDataFile", "Maximum Step", nullptr));
        textLabel1_6->setText(QApplication::translate("ParaDataFile", "ET Step", nullptr));
        textLabel1_8->setText(QApplication::translate("ParaDataFile", "Convergence\n"
"Threshold", nullptr));
        textLabel1_9->setText(QApplication::translate("ParaDataFile", "Krylov\n"
"Dimension", nullptr));
        textLabel1_10->setText(QApplication::translate("ParaDataFile", "Grahm-Schmidt", nullptr));
        comboBoxGrahmSchmidt->setItemText(0, QApplication::translate("ParaDataFile", "Modified", nullptr));
        comboBoxGrahmSchmidt->setItemText(1, QApplication::translate("ParaDataFile", "Classical", nullptr));

        comboBoxGrahmSchmidt->setCurrentText(QApplication::translate("ParaDataFile", "Modified", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("ParaDataFile", "  Model Solver Parameters  ", nullptr));
        textLabel1->setText(QApplication::translate("ParaDataFile", "Start Time", nullptr));
        textLabel2->setText(QApplication::translate("ParaDataFile", "Stop Time", nullptr));
        comboBoxStartStop->setItemText(0, QApplication::translate("ParaDataFile", "Minutes", nullptr));
        comboBoxStartStop->setItemText(1, QApplication::translate("ParaDataFile", "Hours", nullptr));
        comboBoxStartStop->setItemText(2, QApplication::translate("ParaDataFile", "Days", nullptr));
        comboBoxStartStop->setItemText(3, QApplication::translate("ParaDataFile", "Weeks", nullptr));
        comboBoxStartStop->setItemText(4, QApplication::translate("ParaDataFile", "Months", nullptr));
        comboBoxStartStop->setItemText(5, QApplication::translate("ParaDataFile", "Years", nullptr));

        comboBoxStartStop->setCurrentText(QApplication::translate("ParaDataFile", "Minutes", nullptr));
        textLabel3_11->setText(QApplication::translate("ParaDataFile", "Riverbed", nullptr));
        textLabel3_12->setText(QApplication::translate("ParaDataFile", "River", nullptr));
        textLabel3_13->setText(QApplication::translate("ParaDataFile", "Riv u/d", nullptr));
        textLabel3_14->setText(QApplication::translate("ParaDataFile", "Riv S l/r", nullptr));
        textLabel3_15->setText(QApplication::translate("ParaDataFile", "Riv B l/r", nullptr));
        textLabel3_2->setText(QApplication::translate("ParaDataFile", "Snow", nullptr));
        textLabel3->setText(QApplication::translate("ParaDataFile", "Interception", nullptr));
        textLabel3_5->setText(QApplication::translate("ParaDataFile", "Groundwater", nullptr));
        textLabel3_6->setText(QApplication::translate("ParaDataFile", "Ground Evap", nullptr));
        textLabel3_3->setText(QApplication::translate("ParaDataFile", "Surface", nullptr));
        textLabel3_9->setText(QApplication::translate("ParaDataFile", "Recharge", nullptr));
        textLabel3_10->setText(QApplication::translate("ParaDataFile", "Infiltration", nullptr));
        textLabel3_4->setText(QApplication::translate("ParaDataFile", "Soil Moisture", nullptr));
        textLabel3_7->setText(QApplication::translate("ParaDataFile", "Canopy Evap", nullptr));
        textLabel3_8->setText(QApplication::translate("ParaDataFile", "Transpiration", nullptr));
        textLabel3_16->setText(QApplication::translate("ParaDataFile", "Rivbed s", nullptr));
        textLabel3_17->setText(QApplication::translate("ParaDataFile", "Rivbed l/r", nullptr));
        textLabel3_18->setText(QApplication::translate("ParaDataFile", "Rivbed u/d", nullptr));
        comboBoxOutput->setItemText(0, QApplication::translate("ParaDataFile", "Minutes", nullptr));
        comboBoxOutput->setItemText(1, QApplication::translate("ParaDataFile", "Hours", nullptr));
        comboBoxOutput->setItemText(2, QApplication::translate("ParaDataFile", "Days", nullptr));
        comboBoxOutput->setItemText(3, QApplication::translate("ParaDataFile", "Weeks", nullptr));
        comboBoxOutput->setItemText(4, QApplication::translate("ParaDataFile", "Months", nullptr));
        comboBoxOutput->setItemText(5, QApplication::translate("ParaDataFile", "Years", nullptr));

        comboBoxOutput->setCurrentText(QApplication::translate("ParaDataFile", "Minutes", nullptr));
        textLabel3_19->setText(QApplication::translate("ParaDataFile", "Output Intervals in", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("ParaDataFile", " Model Output Parameters", nullptr));
        groupBoxButtons->setTitle(QString());
        pushButtonHelp->setText(QApplication::translate("ParaDataFile", "Help", nullptr));
        pushButtonClose->setText(QApplication::translate("ParaDataFile", "Close", nullptr));
#ifndef QT_NO_TOOLTIP
        pushButtonRun->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pushButtonRun->setText(QApplication::translate("ParaDataFile", "Run", nullptr));
        groupBoxOutput->setTitle(QApplication::translate("ParaDataFile", "Output", nullptr));
        textLabelPara->setText(QApplication::translate("ParaDataFile", "Para Data File", nullptr));
        pushButtonParaDataFile->setText(QApplication::translate("ParaDataFile", "Browse", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ParaDataFile: public Ui_ParaDataFile {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PARADATAFILE_H
